### ISSUE TITLE
Create 'Classes' screen

### ISSUE THREAD

**Issue by CalebMcOlin** [brendenwest/cascade#15]
### Description 

**Objective**:
- let users find bike classes through the mobile app

**Acceptance Criteria**
- App has screen showing list of bike classes corresponding to https://cascade.org/node/6783  
- List should show class categories as sub-heading
- for each class, show image, title, and description
- User can navigate to classes from the drawer navigation menu

**Dependencies**
- api to retrieve list of classes - https://cascade-api.herokuapp.com/classes 
- Icons?

**Open Questions**
- Should class list link to details on web?

**Comment by krishnadave05** [comment]
This feature of Bike Classes has been added to a new branch.
